/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Csv */
        post: operations["upload_csv_api_v1_uploads_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/categorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Categorize Meeting Endpoint */
        post: operations["categorize_meeting_endpoint_api_v1_meetings__meeting_id__categorize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/batch-categorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Categorize Endpoint */
        post: operations["batch_categorize_endpoint_api_v1_meetings_batch_categorize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Endpoint */
        get: operations["get_job_endpoint_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview Endpoint */
        get: operations["overview_endpoint_api_v1_metrics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/by-seller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** By Seller Endpoint */
        get: operations["by_seller_endpoint_api_v1_metrics_by_seller_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/by-industry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** By Industry Endpoint */
        get: operations["by_industry_endpoint_api_v1_metrics_by_industry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/objections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Objections Endpoint */
        get: operations["objections_endpoint_api_v1_metrics_objections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/discovery-channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discovery Channels Endpoint */
        get: operations["discovery_channels_endpoint_api_v1_metrics_discovery_channels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_csv_api_v1_uploads_csv_post */
        Body_upload_csv_api_v1_uploads_csv_post: {
            /** File */
            file: string;
        };
        /** CategorizationResponse */
        CategorizationResponse: {
            /** Id */
            id: number;
            /** Meeting Id */
            meeting_id: number;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            industry: components["schemas"]["Industry"];
            use_case: components["schemas"]["UseCase"];
            /** Interest Level */
            interest_level: number;
            /** Sentiment */
            sentiment: number;
            urgency: components["schemas"]["Urgency"];
            /** Volume Amount */
            volume_amount: number | null;
            volume_period: components["schemas"]["VolumePeriod"] | null;
            discovery_channel: components["schemas"]["DiscoveryChannel"];
            /** Integration Required */
            integration_required: boolean;
            /** Systems Mentioned */
            systems_mentioned: string[];
            /** Main Objection */
            main_objection: string | null;
            /** Competitors Mentioned */
            competitors_mentioned: string[];
            personalization_concern: components["schemas"]["PersonalizationConcern"];
            data_sensitivity: components["schemas"]["DataSensitivity"];
            /** Close Probability */
            close_probability: number;
            customer_segment: components["schemas"]["CustomerSegment"];
            /** Key Topics */
            key_topics: string[];
            /** Summary Es */
            summary_es: string;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CustomerSegment
         * @enum {string}
         */
        CustomerSegment: "smb" | "midmarket" | "enterprise" | "unknown";
        /**
         * DataSensitivity
         * @enum {string}
         */
        DataSensitivity: "low" | "medium" | "high";
        /**
         * DiscoveryChannel
         * @enum {string}
         */
        DiscoveryChannel: "conference" | "referral" | "google_search" | "linkedin" | "podcast" | "webinar" | "forum" | "trade_fair" | "other";
        /** DiscoveryChannelMetric */
        DiscoveryChannelMetric: {
            discovery_channel: components["schemas"]["DiscoveryChannel"];
            /** Total Meetings */
            total_meetings: number;
            /** Closed Meetings */
            closed_meetings: number;
            /** Close Rate */
            close_rate: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Industry
         * @enum {string}
         */
        Industry: "financial_services" | "healthcare" | "retail_ecommerce" | "education" | "logistics" | "hospitality" | "real_estate" | "saas_tech" | "legal" | "marketing" | "manufacturing" | "nonprofit" | "other";
        /** IndustryMetric */
        IndustryMetric: {
            industry: components["schemas"]["Industry"];
            /** Total Meetings */
            total_meetings: number;
            /** Closed Meetings */
            closed_meetings: number;
            /** Close Rate */
            close_rate: number;
            /** Avg Close Probability */
            avg_close_probability: number;
        };
        /** IngestError */
        IngestError: {
            /** Row */
            row: number;
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
        };
        /** IngestSummary */
        IngestSummary: {
            /** Total Rows */
            total_rows: number;
            /** Inserted */
            inserted: number;
            /** Skipped Duplicates */
            skipped_duplicates: number;
            /** Errors */
            errors?: components["schemas"]["IngestError"][];
            /** New Sellers */
            new_sellers?: string[];
        };
        /** JobError */
        JobError: {
            /** Meeting Id */
            meeting_id: number;
            /** Error */
            error: string;
        };
        /** JobResponse */
        JobResponse: {
            /** Id */
            id: number;
            status: components["schemas"]["JobStatus"];
            /** Total */
            total: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Cached */
            cached: number;
            /** Errors */
            errors: components["schemas"]["JobError"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "completed" | "failed";
        /** ObjectionMetric */
        ObjectionMetric: {
            /** Objection */
            objection: string;
            /** Count */
            count: number;
            /** Frequency Pct */
            frequency_pct: number;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Total Meetings */
            total_meetings: number;
            /** Closed Meetings */
            closed_meetings: number;
            /** Close Rate */
            close_rate: number;
            /** Avg Sentiment */
            avg_sentiment: number | null;
            /** Avg Close Probability */
            avg_close_probability: number | null;
            top_industry: components["schemas"]["Industry"] | null;
            top_discovery_channel: components["schemas"]["DiscoveryChannel"] | null;
        };
        /**
         * PersonalizationConcern
         * @enum {string}
         */
        PersonalizationConcern: "low" | "medium" | "high";
        /** SellerMetric */
        SellerMetric: {
            /** Seller Id */
            seller_id: number;
            /** Seller Name */
            seller_name: string;
            /** Total Meetings */
            total_meetings: number;
            /** Closed Meetings */
            closed_meetings: number;
            /** Close Rate */
            close_rate: number;
            /** Avg Sentiment */
            avg_sentiment: number;
            /** Avg Interest Level */
            avg_interest_level: number;
            /** Avg Close Probability */
            avg_close_probability: number;
        };
        /**
         * Urgency
         * @enum {string}
         */
        Urgency: "low" | "medium" | "high";
        /**
         * UseCase
         * @enum {string}
         */
        UseCase: "customer_support" | "technical_support" | "sales_inquiries" | "bookings_reservations" | "logistics_tracking" | "internal_ops" | "other";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VolumePeriod
         * @enum {string}
         */
        VolumePeriod: "daily" | "weekly" | "monthly";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    upload_csv_api_v1_uploads_csv_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_csv_api_v1_uploads_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categorize_meeting_endpoint_api_v1_meetings__meeting_id__categorize_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_categorize_endpoint_api_v1_meetings_batch_categorize_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_endpoint_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_endpoint_api_v1_metrics_overview_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                seller_id?: number | null;
                industry?: components["schemas"]["Industry"] | null;
                closed?: boolean | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    by_seller_endpoint_api_v1_metrics_by_seller_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                seller_id?: number | null;
                industry?: components["schemas"]["Industry"] | null;
                closed?: boolean | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellerMetric"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    by_industry_endpoint_api_v1_metrics_by_industry_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                seller_id?: number | null;
                industry?: components["schemas"]["Industry"] | null;
                closed?: boolean | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustryMetric"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    objections_endpoint_api_v1_metrics_objections_get: {
        parameters: {
            query?: {
                limit?: number;
                from?: string | null;
                to?: string | null;
                seller_id?: number | null;
                industry?: components["schemas"]["Industry"] | null;
                closed?: boolean | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectionMetric"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discovery_channels_endpoint_api_v1_metrics_discovery_channels_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                seller_id?: number | null;
                industry?: components["schemas"]["Industry"] | null;
                closed?: boolean | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryChannelMetric"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
