"""initial_schema

Revision ID: 1f4bce0e8732
Revises:
Create Date: 2026-04-25 20:09:47.738629

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1f4bce0e8732"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sellers",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sellers")),
        sa.UniqueConstraint("name", name=op.f("uq_sellers_name")),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
            name=op.f("fk_customers_seller_id_sellers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_table(
        "meetings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("seller_id", sa.BigInteger(), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("closed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("transcript_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_meetings_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
            name=op.f("fk_meetings_seller_id_sellers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meetings")),
        sa.UniqueConstraint("transcript_hash", name=op.f("uq_meetings_transcript_hash")),
    )
    op.create_index("ix_meetings_closed", "meetings", ["closed"], unique=False)
    op.create_index(
        "ix_meetings_seller_date", "meetings", ["seller_id", "meeting_date"], unique=False
    )
    op.create_table(
        "categorizations",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("meeting_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("raw_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "industry",
            sa.Enum(
                "financial_services",
                "healthcare",
                "retail_ecommerce",
                "education",
                "logistics",
                "hospitality",
                "real_estate",
                "saas_tech",
                "legal",
                "marketing",
                "manufacturing",
                "nonprofit",
                "other",
                name="industry",
            ),
            nullable=False,
        ),
        sa.Column(
            "use_case",
            sa.Enum(
                "customer_support",
                "technical_support",
                "sales_inquiries",
                "bookings_reservations",
                "logistics_tracking",
                "internal_ops",
                "other",
                name="use_case",
            ),
            nullable=False,
        ),
        sa.Column("interest_level", sa.Integer(), nullable=False),
        sa.Column("sentiment", sa.Float(), nullable=False),
        sa.Column("urgency", sa.Enum("low", "medium", "high", name="urgency"), nullable=False),
        sa.Column("volume_amount", sa.Integer(), nullable=True),
        sa.Column(
            "volume_period",
            sa.Enum("daily", "weekly", "monthly", name="volume_period"),
            nullable=True,
        ),
        sa.Column(
            "discovery_channel",
            sa.Enum(
                "conference",
                "referral",
                "google_search",
                "linkedin",
                "podcast",
                "webinar",
                "forum",
                "trade_fair",
                "other",
                name="discovery_channel",
            ),
            nullable=False,
        ),
        sa.Column("integration_required", sa.Boolean(), nullable=False),
        sa.Column(
            "systems_mentioned", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "competitors_mentioned",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("main_objection", sa.Text(), nullable=True),
        sa.Column(
            "personalization_concern",
            sa.Enum("low", "medium", "high", name="personalization_concern"),
            nullable=False,
        ),
        sa.Column(
            "data_sensitivity",
            sa.Enum("low", "medium", "high", name="data_sensitivity"),
            nullable=False,
        ),
        sa.Column("close_probability", sa.Float(), nullable=False),
        sa.Column(
            "customer_segment",
            sa.Enum("smb", "midmarket", "enterprise", "unknown", name="customer_segment"),
            nullable=False,
        ),
        sa.Column("key_topics", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("summary_es", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
            name=op.f("fk_categorizations_meeting_id_meetings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categorizations")),
        sa.UniqueConstraint(
            "meeting_id", "prompt_version", "model", name="uq_categorizations_meeting_prompt_model"
        ),
    )
    op.create_index("ix_categorizations_industry", "categorizations", ["industry"], unique=False)
    op.create_index(
        "ix_categorizations_key_topics",
        "categorizations",
        ["key_topics"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_categorizations_key_topics", table_name="categorizations", postgresql_using="gin"
    )
    op.drop_index("ix_categorizations_industry", table_name="categorizations")
    op.drop_table("categorizations")
    op.drop_index("ix_meetings_seller_date", table_name="meetings")
    op.drop_index("ix_meetings_closed", table_name="meetings")
    op.drop_table("meetings")
    op.drop_table("customers")
    op.drop_table("sellers")
    # ### end Alembic commands ###

    # Drop ENUM types creados por sa.Enum a nivel de columna — no los borra drop_table.
    for enum_name in (
        "industry",
        "use_case",
        "urgency",
        "volume_period",
        "discovery_channel",
        "personalization_concern",
        "data_sensitivity",
        "customer_segment",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
